[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "serif" # Ini akan mengubah font jadi mirip Times New Roman / Roboto tergantung OS
